### ISSUE TITLE
data

### ISSUE THREAD

**Issue by dongkun211** [a11to1n3/StatFilterAppliedInSTLFDeeplearning#1]
Can you upload the data used?

**Comment by a11to1n3** [comment]
Hi, there are public datasets you can acquire as the use case: NYISO and PJM-RTO.

**Comment by dongkun211** [comment]
thanks

**Comment by a11to1n3** [comment]
Please cite this article if you decide to use it:  Duong Minh Bui, Phuc Duy Le, Minh Tien Cao, Trang Thi Pham & Duy Anh Pham (2020) Accuracy improvement of various short-term load forecasting models by a novel and unified statistical data-filtering method, International Journal of Green Energy, 17:7, 382-406, DOI: 10.1080/15435075.2020.1761810
